### ISSUE TITLE
Right click on info window causes map to zoom

### ISSUE THREAD

**Issue by Joel-Kravets** [atmist/snazzy-info-window#1]
The info window adds a DOM listener for mouse events which stops event propagation to the map. We will have to look into why the right click event ignores this DOM listener.

**Comment by Joel-Kravets** [comment]
The info window uses the same stop event propagation handler for a lot of mouse events (including 'rightclick'). This doesn't stop the map from zooming out when double right clicking on the info window. I looked through a variety of solutions online but nothing seemed to work consistently.

If you really need to disable this feature you can use the following option.
```js
var map = new google.maps.Map(div, {
    // Your settings
    disableDoubleClickZoom: true
});
```

**Comment by joelkravets** [comment]
Looking through the info bubble source code we noticed that the `contextmenu` was also being handled. It seems that by stopping the propagation of this event all the weird right click issues are now gone.
