### ISSUE TITLE
Multiple Maps infoWindow renders on the first

### ISSUE THREAD

**Issue by nwyler-modusagency** [atmist/snazzy-info-window#14]
I want to have more than 1 map but the infowindows always renders in the first map.

**Comment by joelkravets** [comment]
When creating the info window make sure that the supplied marker is added to the correct map.

`var infoWindow = new SnazzyInfoWindow({
    marker: marker,
    content: 'Snazzy!'
});`

If you could provide me with some example code I could take a look and see what is going on. For now I will assume that this is not a bug in the project itself.
