### ISSUE TITLE
Individual Info box placement

### ISSUE THREAD

**Issue by jmelendev** [atmist/snazzy-info-window#17]
Can we set individual placements per each info box? I.E. Have one location placement on the left and another on the bottom?

**Comment by joelkravets** [comment]
Do you mean something like the [multiple markers example](https://rawgit.com/atmist/snazzy-info-window/master/examples/multiple-markers/index.html)?

**Comment by jmelendev** [comment]
My apologies, I as soon as i asked I realized the solution. Thanks for the quick response though!
