### ISSUE TITLE
Application in Adobe Muse CC?

### ISSUE THREAD

**Issue by designbykieran** [atmist/snazzy-info-window#18]
Not so much of an issue, more of a question. Any ideas of how I'd go about applying this to a custom styled google map, created in Muse via the 'insert HTML' function and Snazzymaps. 

My question is this, how would I go about adding the 'snazzy-info-window' to the map? I've tried adding the section of js under "  // Add a Snazzy Info Window to the marker" within the supplied scripts.js file to my existing HTML element within muse, however it has no effect. It just 'breaks' the map, so my original grey rectangle (used to create the map with JS). 

If this doesn't make sense, it may help to refer to the video tutorial I followed > https://www.youtube.com/watch?v=M_h9Ni3c2eI

Any help would be greatly appreciated, it is also worth noting that I have also linked the stylesheet and JS script into the head of the page (taken from the index.html within the JS Styles folder supplied).

Thanks in advance!

**Comment by DarcyChan** [comment]
I'm not too familiar with Muse. Is the Google Maps script being added before the Snazzy Info Windows script? Perhaps try something like this in your 'insert HTML' block (and removing the info window script in the head):

```
// Google Maps
<script src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY"></script>

// Snazzy Info Windows
<script src="snazzy-info-window.min.js"></script>

// Create the map and info window
<script>...</script>
```
