### ISSUE TITLE
Snazzywindow placement option not working

### ISSUE THREAD

**Issue by gmanojisaac** [atmist/snazzy-info-window#22]
/**
     * Choose where you want the info window to be displayed, relative to the marker.
     */
    placement: 'top' | 'bottom' | 'left' | 'right';

Only top works.

**Comment by joelkravets** [comment]
Checkout the [multiple marker example](https://rawgit.com/atmist/snazzy-info-window/master/examples/multiple-markers/index.html) where all 4 positions are used at once.
