### ISSUE TITLE
Create more examples before release

### ISSUE THREAD

**Issue by adamkrogh** [atmist/snazzy-info-window#3]
We could use a lot more examples showing how specific features of the library are used. These would be good to complete before we officially release the library.

- [x] Organize the examples and decide on a format
- [x] Simple example
- [x] Multiple markers
- [x] Dynamic content
- [x] Alternate styles

**Comment by DarcyChan** [comment]
We have added some styling examples that utilize a combination of SCSS and JavaScript.
