### ISSUE TITLE
A setLocation() method

### ISSUE THREAD

**Issue by vampirefrog** [atmist/snazzy-info-window#4]
Hello, please add a method for moving the snazzyInfoWindow, similar to google.maps.InfoWindow setPosition(). That would be very useful, thanks!

**Comment by adamkrogh** [comment]
Hey, that's a good idea. I think it should be possible. We'll look into it and see if we can get a new release out soon (maybe next week).

**Comment by talentedaamer** [comment]
Hi @adamkrogh did you add this feature.

**Comment by adamkrogh** [comment]
Sorry, we're a bit swamped at the moment. We're going to try and schedule some time for the next release soon.

**Comment by adamkrogh** [comment]
We've just published version 1.1.0 that includes this change. Let us know how it looks!
