### ISSUE TITLE
Info window opening far away from the marker

### ISSUE THREAD

**Issue by saintsweeto** [atmist/snazzy-info-window#52]
I have a simple code:
`let infoWindow = new SnazzyInfoWindow({
                marker,
                content,
                closeWhenOthersOpen: true,
                callbacks: {
                    open: function() {
                        // Show modal
                    },
                }
            `});``
            
            but it seems to be opening far away from the marker

**Comment by tarikc91** [comment]
I have the same problem. Even with using `position`. The info window also follows the bounding box and is displayed always in the center

**Comment by tarikc91** [comment]
@saintsweeto You have to include the css for the info window

**Comment by saintsweeto** [comment]
It doesn't work. I'm using webpack! 
`const SnazzyInfoWindow = require('snazzy-info-window');`
