### ISSUE TITLE
Close previous window before opening new

### ISSUE THREAD

**Issue by richlewis14** [atmist/snazzy-info-window#6]
Hi,

Is it possible to set behaviour as stated in the title? So if i click on a marker to open a snazzy info window can it close the current open window (if open), the idea being that only one window is open at any one time.

Thanks

**Comment by joelkravets** [comment]
Hi Richard,

We could implement this by triggering a custom event after an info window has opened.

`google.maps.event.trigger(this.getMap(), 'snazzy-info-window-opened', this);`

I can't provide an ETA since we are really swamped in the office lately, but keep an eye out for our next release.

**Comment by joelkravets** [comment]
We've just published version 1.1.0 that includes this change. Let us know how it looks!

**Comment by richlewis14** [comment]
Wow thanks guys, that was fast... I'll check it out in the morning 😀
